models/Technology.php
<?php

namespace app\models;

use yii\db\Query;

class Technology extends \app\tables\Technology
{
    public static function all()
    {
        return (new Query())
            ->select([
                'technology.id',
                'technology.alias',
                'technology.title',
                '(SELECT upload."name" FROM upload WHERE upload.id = technology.cover_image_id) AS src',
            ])
            ->from('technology')
            ->orderBy('sort')
            ->all();
    }

    public static function mainPage()
    {
        return (new Query())
            ->select([
                'technology.alias',
                'technology.intro',
                'technology.title',
                'technology.image',
                '(SELECT upload."name" FROM upload WHERE upload.id = technology.cover_image_id) AS src',
            ])
            ->from('technology')
            ->where(['and','main_page','status'])
            ->orderBy('sort')
            ->all();
    }

    public static function one($alias)
    {
        return (new Query())
            ->select([
                'technology.alias',
                'technology.title',
                'technology.image',
                'technology.text',
            ])
            ->from('technology')
            ->where(['alias' => $alias])
            ->one();
    }

    public static function oneByAlias($alias)
    {
        return self::find()
            ->select([
                '*',
            ])
            ->where(['alias' => $alias])
            ->one();
    }
}

controllers/TechnologyController.php
<?php

namespace app\controllers;

use app\models\Technology;
use app\components\Info;
use app\tables\TechnologyUploads;
use MongoDB\Collection;
use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use app\lib\My;
use yii\web\NotFoundHttpException;

class TechnologyController extends Controller
{
    public function actionIndex()
    {
        $uri = My::getUri();
        $current = new Technology();
        $current->id = 0;
        $current->title = 'Технологии нанесения';
        $this->view->title = $current->title;
        $current->alias = end($uri);
//        $technologies = Technology::all();
        $technologies = Technology::find()
            ->asArray()
            ->select([
                'technology.id',
                'technology.alias',
                'technology.title',
                '(SELECT upload."name" FROM upload WHERE upload.id = technology.cover_image_id) AS src',
            ])
            ->where('status')
            ->orderBy('sort')
            ->all();
        Url::remember();

        return $this->render('index', [
            'technologies' => $technologies,
            'current' => $current,
        ]);
    }

    public function actionView($alias)
    {
        $uri = $uri = My::getUri();
        /** @var Technology $current */
        $current = Technology::oneByAlias(end($uri));
        if (!$current || !$current->status) {
            throw new NotFoundHttpException;
        }

        $parent = new Technology();
        $parent['id'] = 0;
        $parent['title'] = 'Технологии нанесения';
        $parent['alias'] = $uri[0];

        $technologies = Technology::all();
        $images = TechnologyUploads::find()
            ->asArray()
            ->select([
                'name'
            ])
            ->where([
                'technology_id' => $current->id
            ])
            ->innerJoin('upload', 'technology_uploads.upload_id = upload.id')
            ->column();
        $main_image = $current->coverImage->name;

        $sum = Info::get('min_sum');
        $this->view->title = $current->meta_title ?: $current->title;

        Url::remember();

        return $this->render('view', [
            'technologies' => $technologies,
            'current' => $current,
            'parent' => $parent,
            'sum' => $sum,
            'images' => $images,
            'main_image' => $main_image
        ]);
    }
}

views/technology/index.php
<?php
/**
 * @var $this yii\web\View
 * @var $model
 */
use app\lib\My;
use yii\helpers\Html;
use yii\helpers\Url;
use app\widgets\Requirements;
use app\widgets\LeftNav;

$this->registerMetaTag(['name' => 'keywords', 'content' => $this->params['main_meta']['keywords']]);
$this->registerMetaTag(['name' => 'description', 'content' => $this->params['main_meta']['description']]);

?>
<div class="col-md-3 aside">
    <div class="mini-block">
        <div class="footer">
            <ul class="list-unstyled">
                <?php
                echo LeftNav::widget([
                    'list' => $technologies,
                    'category' => $current,
                    'previous' => $current['alias'] . '/',
                    'current' => $current['alias'],
                    'type' => 'pages'
                ]) ?>
            </ul>
        </div>
    </div>
    <?= Requirements::widget() ?>

</div>
<div class="col-md-9">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li><a href="/">Главная</a></li>
            <li class="active">Технологии нанесения</li>
        </ol>
    </div>
    <div class="col-lg-12">
        <h1>Технологии нанесения</h1>
        <hr>
    </div>
    <div class="col-lg-12 technology">
        <div class="row">
            <?php foreach ($technologies as $m): ?>
                <div class="col-md-4">
                    <a href="<?= Url::to(['/technology/view', 'alias' => $m['alias']]) ?>" class="link">
                        <div class="box">
                            <div
                                class="image"><?= Html::img(My::thumb('/uploads/images/thumbs/' . $m['src'])) ?></div>
                        </div>
                        <div class="title"><?= $m['title'] ?></div>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

views/technology/view.php
<?php
/**
 * @var $this yii\web\View
 * @var $technologies
 * @var array $images
 * @var float $sum
 * @var \app\models\Technology $current
 * @var \app\models\Technology $parent
 * @var string $main_image
 */
use app\assets\MagnificPopupAsset;
use app\widgets\Requirements;
use yii\helpers\Html;
use yii\helpers\Url;
use app\widgets\LeftNav;

MagnificPopupAsset::register($this);

$this->registerMetaTag(['name' => 'keywords', 'content' => $current->meta_keywords ?: $this->params['main_meta']['keywords']]);
$this->registerMetaTag(['name' => 'description', 'content' => $current->meta_description ?: $this->params['main_meta']['description']]);

?>

<div class="col-md-3 aside">
    <div class="mini-block">
        <div class="footer">
            <ul class="list-unstyled">
                <?php echo LeftNav::widget([
                    'list' => $technologies,
                    'category' => $parent,
                    'previous' => $parent['alias'] . '/',
                    'current' => $current['alias'],
                    'type' => 'pages'
                ]) ?>
            </ul>
        </div>
    </div>
    <?= Requirements::widget() ?>
</div>
<div class="col-md-9">
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li><a href="/">Главная</a></li>
                <li><a href="<?= Url::to(['/technology/index']) ?>">Технологии нанесения</a></li>
                <li class="active"><?= $current['title']; ?></li>
            </ol>
        </div>
        <div class="col-lg-12">
            <a class="btn-calc" type="button" data-toggle="modal" data-target="#calcModal">
                <i class="ion-calculator"></i>Расчет стоимости
            </a>
            <h1><?= $current['title']; ?></h1>
            <hr>
        </div>
        <div class="col-lg-12 technology">
            <?= $current['text']; ?>
            <?php if ($images): ?>
                <div class="works-description">Примеры работ</div>
                <div class="works popup-gallery">
                    <?php foreach ($images as $image) : ?>
                        <div class="item">
                            <a href="/uploads/images/<?= $image ?>">
                                <img src="/uploads/images/thumbs100/<?= $image ?>" alt="">
                            </a>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<div class="modal fade" id="calcModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="row">
            <div class="col-xs-6 col-xs-offset-3">
                <div class="modal-content">
                    <div class="modal-body calc-description">
                        <i class="ion-alert"></i>
                        <p>
                            Сумма минимального заказа - <span><?= $sum ?> руб</span>
                        </p>
                        <p>
                            Средний срок выполнения заказа - 3 дня
                        </p>
                        <p>
                            (при 100% оплате и согласованном макете)
                        </p>
                        <p>
                            Наличие товара уточняйте у менеджера.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <div class="modal-content">
                    <div class="modal-body calc-image">
                        <div class="calc-text-name">
                            <?= $current['title'] ?>
                        </div>
                        <hr>
                        <?= Html::img(["/uploads/images/thumbs/$main_image"]) ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="modal-content">
                    <div class="modal-body calc-form">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <?= is_file(__DIR__ . '/calc/' . $current['alias'] . '.php') ?
                            $this->render("calc/$current[alias]") :
                            'Раздел в наполнении' ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-3">
                <div class="modal-content">
                    <div class="modal-body calc-price">
                        <p class="text-align_right">
                            Предварительный расчет
                        </p>
                        <p class="">
                            Цена нанесения на 1 шт
                        </p>
                        <p class="text-align_right">
                            <span class="price">

                            </span>
                        </p>
                        <p class="">
                            Цена может меняться в зависимости от тиража
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>